# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 Fundament Software SPC <https://fundament.software>

[graph]
targets = []
all-features = false
no-default-features = false
exclude = []

[output]
feature-depth = 1

[advisories]
db-path = "$CARGO_HOME/advisory-dbs"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = ["RUSTSEC-2024-0436"]
[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Zlib",
    "MPL-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "Unicode-3.0",
    "CC0-1.0",
    "ISC",
    "BSL-1.0",
]
confidence-threshold = 0.8

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "allow"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com/pop-os/cosmic-text"]
