# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 Fundament Software SPC <https://fundament.software>

permissions:
  contents: read

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # run weekly
    - cron: '0 0 * * 0'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        rust:
          - nightly
          - beta
          - stable
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      run: rustup update ${{ matrix.rust }} --no-self-update && rustup default ${{ matrix.rust }}

    - name: Install Clang
      run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt install -y clang-15
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-15 60
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-15 60

    - name: Build
      run: cargo build --all

    - name: Build in release mode
      run: cargo build --all --release

    # We can't run any tests, because they would need a window manager and graphics to exist, which aren't available on standard CI

  fmt:
    name: formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check --unstable-features

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: EmbarkStudios/cargo-deny-action@v2
      with:
        log-level: warn
        command: check
        arguments: --all-features

  # Check for typos in the repository based on a static dictionary
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # This is pinned to a specific version because the typos dictionary can
      # be updated between patch versions, and a new dictionary can find new
      # typos in the repo thus suddenly breaking CI unless we pin the version.
      - uses: crate-ci/typos@v1.34.0
